### ISSUE TITLE
"Copy QR Code to clipboard" error in Firefox

### ISSUE THREAD

**Issue by jshwlkr** [lyqht/styled-qr-code-generator#21]
Seeing an error in Firefox and the copy does not work.

```
Uncaught (in promise) ReferenceError: ClipboardItem is not defined
    UL https://styled-qr-code-generator.vercel.app/assets/index-be8c1718.js:28
    promise callback*UL https://styled-qr-code-generator.vercel.app/assets/index-be8c1718.js:28
    de https://styled-qr-code-generator.vercel.app/assets/index-be8c1718.js:28
    Rt https://styled-qr-code-generator.vercel.app/assets/index-be8c1718.js:1
    at https://styled-qr-code-generator.vercel.app/assets/index-be8c1718.js:1
    n https://styled-qr-code-generator.vercel.app/assets/index-be8c1718.js:1

```

**Comment by lyqht** [comment]
hi @jshwlkr sorry for the long delay, haven't got time to work on side projects for a while,  I tried looking around for a while, but it seems that Firefox doesn't have great support for Clipboard API. They do have an option for you to manually turn it on though if you want to.

To enable this feature on Firefox, you would have to go to `about:config` URL in your Firefox browser, and then switch on the clipboardItem API.

![CleanShot 2024-01-05 at 16 39 58@2x](https://github.com/lyqht/styled-qr-code-generator/assets/35736525/c8b2b049-41ad-4f7e-872a-2b9f341fe5a3)

After that it should work.
