### ISSUE TITLE
CORS issue for certain external logo image links

### ISSUE THREAD

**Issue by lyqht** [lyqht/styled-qr-code-generator#3]
If you use any SVG link from [Icones](https://icones.js.org/), it works as intended, however for certain links like

https://uilicious.com/assets/images/brand/cake_logo.svg

There's a CORS issue
<img width="565" alt="image" src="https://github.com/lyqht/styled-qr-code-generator/assets/35736525/cab025eb-ffaa-492f-8fd9-b02e3e44cf9b">

This shouldn't happen. **Seems to be stemmed from the qr-code-styling library where there's many issues about CORS that are left open.**

**Comment by itsAnuga** [comment]
Will be hard to make external sites to change their CORS rules ;)

**Comment by lyqht** [comment]
## Workaround

If you encounter this issue, a workaround is to just upload ur image for the logo instead of using an external link
